# Enable BuildKit
version: '3.8'

networks:
  net:
    driver: bridge

services:
  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chroma-db
    volumes:
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
      # Read more about deployments: https://docs.trychroma.com/deployment
      - chroma:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
    # possible values are: "no", always", "on-failure", "unless-stopped"
    #restart: unless-stopped 
    ports:
      - "8000:8000"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 2G

  ytai:
    image: sudoleg/yotube-gpt:latest
    container_name: youtube-gpt
    depends_on:
      chromadb:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - sudoleg/yotube-gpt:latest
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      # replace the part before : with the path
      # to the directory where you would like
      # the summaries to be saved
      - E:\Documents\yt-summaries:/app/responses
      # leave as it is
      - ./data:/app/data
    ports:
      - "8501:8501"
    networks:
      - net
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  chroma:
    driver: local
